<script>
	import TikTokThumbnail from '$lib/TikTokThumbnail.svelte';
	import { base } from '$app/paths';
</script>

<div class="w-100">
	<div class="d-flex flex-wrap justify-content-center">
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84duJXY/"
			img="{base}/tiktok/hairspray.jpg"
			views="4.8M"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dp7tq/"
			img="{base}/tiktok/kdrama.jpg"
			views="263K"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84d59wr/"
			img="{base}/tiktok/vitamix.jpg"
			views="166K"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dsYtm/"
			img="{base}/tiktok/apple.jpg"
			views="5.3M"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dnABX/"
			img="{base}/tiktok/poc.jpg"
			views="429K"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dXgpB/"
			img="{base}/tiktok/pizza.jpg"
			views="3.3M"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dx22E/"
			img="{base}/tiktok/graduate.jpg"
			views="1.7M"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84d4fsU/"
			img="{base}/tiktok/cake.jpg"
			views="51K"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dn7gd/"
			img="{base}/tiktok/candle.jpg"
			views="1.6M"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dq8Bf/"
			img="{base}/tiktok/healthcare.jpg"
			views="581K"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84dbBHF/"
			img="{base}/tiktok/ipad.jpg"
			views="410K"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84d92XK/"
			img="{base}/tiktok/minecraft.jpg"
			views="63K"
		/>
		<TikTokThumbnail
			url="https://www.tiktok.com/t/ZT84du1dJ/"
			img="{base}/tiktok/mask.jpg"
			views="225K"
		/>
	</div>
</div>
